// src/pages/Login.tsx
"use client";

import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Snowflake, Lock, User, ArrowLeft, HelpCircle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from '@/components/ui/card';
import { showError, showSuccess } from '@/utils/toast';
import { UserProfile } from '@/components/UserAdminSettings';

const Login = () => {
  const [identifier, setIdentifier] = React.useState('');
  const [password, setPassword] = React.useState('');
  const navigate = useNavigate();

  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();
    
    const savedUsers = localStorage.getItem('lider_users');
    let users: UserProfile[] = savedUsers ? JSON.parse(savedUsers) : [];
    
    // Se não houver usuários, cria o admin padrão para permitir o primeiro acesso
    if (users.length === 0) {
      const defaultAdmin: UserProfile = {
        id: '1',
        username: 'admin',
        email: 'admin@lider.com',
        password: '1234',
        role: 'ADMIN',
        permissions: {
          estoque: { view: true, edit: true, delete: true },
          orcamentos: { view: true, edit: true, delete: true },
          clientes: { view: true, edit: true, delete: true },
          historico: { view: true, edit: true, delete: true },
          config: { view: true, edit: true, delete: true },
        }
      };
      users = [defaultAdmin];
      localStorage.setItem('lider_users', JSON.stringify(users));
    }
    
    const user = users.find(u => 
      (u.username === identifier || u.email === identifier) && u.password === password
    );

    if (user) {
      showSuccess(`Bem-vindo, ${user.username}!`);
      localStorage.setItem('isLoggedIn', 'true');
      localStorage.setItem('currentUser', JSON.stringify(user));
      navigate('/dashboard');
    } else {
      showError('Usuário/E-mail ou senha incorretos.');
    }
  };

  const handleForgotPassword = () => {
    showSuccess('Por favor, entre em contato com o administrador do sistema para redefinir sua senha.');
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-blue-50 dark:bg-slate-950 p-4 transition-colors">
      <div className="absolute top-8 left-8">
        <Button variant="ghost" onClick={() => navigate('/')} className="text-blue-600 dark:text-blue-400">
          <ArrowLeft className="mr-2 h-4 w-4" /> Voltar ao site
        </Button>
      </div>
      
      <Card className="w-full max-w-md shadow-xl border-blue-100 dark:border-slate-800 dark:bg-slate-900">
        <CardHeader className="space-y-1 text-center">
          <div className="flex justify-center mb-4">
            <div className="bg-blue-600 p-3 rounded-2xl">
              <Snowflake className="h-8 w-8 text-white" />
            </div>
          </div>
          <CardTitle className="text-2xl font-bold text-blue-900 dark:text-white">Gestão Lider</CardTitle>
          <CardDescription className="dark:text-gray-400">Entre com seu usuário ou e-mail</CardDescription>
        </CardHeader>
        <form onSubmit={handleLogin}>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <div className="relative">
                <User className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
                <Input 
                  placeholder="Usuário ou E-mail" 
                  className="pl-10 dark:bg-slate-950 dark:border-slate-800"
                  value={identifier}
                  onChange={(e) => setIdentifier(e.target.value)}
                  required
                />
              </div>
            </div>
            <div className="space-y-2">
              <div className="relative">
                <Lock className="absolute left-3 top-3 h-4 w-4 text-gray-400" />
                <Input 
                  type="password" 
                  placeholder="Senha" 
                  className="pl-10 dark:bg-slate-950 dark:border-slate-800"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  required
                />
              </div>
              <div className="flex justify-end">
                <button 
                  type="button"
                  onClick={handleForgotPassword}
                  className="text-xs text-blue-600 dark:text-blue-400 hover:underline flex items-center gap-1"
                >
                  <HelpCircle size={12} />
                  Esqueceu a senha?
                </button>
              </div>
            </div>
          </CardContent>
          <CardFooter>
            <Button type="submit" className="w-full bg-blue-600 hover:bg-blue-700 text-white py-6 text-lg">
              Entrar no Sistema
            </Button>
          </CardFooter>
        </form>
      </Card>
    </div>
  );
};

export default Login;

// src/views/Login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-blue-50 dark:bg-slate-950 p-4 transition-colors">
    <div class="absolute top-8 left-8">
      <router-link to="/" class="flex items-center gap-2 text-sm font-medium text-blue-600 dark:text-blue-400 hover:text-blue-800 transition">
        <ArrowLeft class="h-4 w-4" /> Voltar ao site
      </router-link>
    </div>
    
    <div class="w-full max-w-md bg-white dark:bg-slate-900 shadow-xl border border-blue-100 dark:border-slate-800 rounded-xl overflow-hidden">
      <!-- Header do Card -->
      <div class="p-6 text-center space-y-2 border-b border-gray-100 dark:border-slate-800">
        <div class="flex justify-center mb-4">
          <div class="bg-blue-600 p-3 rounded-2xl shadow-lg ring-4 ring-blue-50/50 dark:ring-slate-800/50">
            <Snowflake class="h-8 w-8 text-white" />
          </div>
        </div>
        <h2 class="text-2xl font-bold text-blue-900 dark:text-white tracking-tight">Gestão Lider</h2>
        <p class="text-sm text-gray-500 dark:text-gray-400">Entre com seu usuário ou e-mail</p>
      </div>

      <!-- Corpo do Formulário -->
      <form @submit.prevent="handleLogin" class="p-6 space-y-6">
        <div class="space-y-4">
          <div class="relative">
            <User class="absolute left-3 top-3 h-4 w-4 text-gray-400" />
            <input 
              v-model="identifier"
              type="text"
              placeholder="Usuário ou E-mail"
              class="w-full pl-10 pr-4 py-2 border border-gray-200 dark:border-slate-800 rounded-lg outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 bg-white dark:bg-slate-950 dark:text-white transition"
              required
            />
          </div>

          <div class="relative">
            <Lock class="absolute left-3 top-3 h-4 w-4 text-gray-400" />
            <input 
              v-model="password"
              type="password"
              placeholder="Senha"
              class="w-full pl-10 pr-4 py-2 border border-gray-200 dark:border-slate-800 rounded-lg outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500 bg-white dark:bg-slate-950 dark:text-white transition"
              required
            />
          </div>
          
          <div class="flex justify-end">
            <button 
              type="button" 
              @click="handleForgot"
              class="text-xs text-blue-600 dark:text-blue-400 hover:underline flex items-center gap-1 font-medium transition"
            >
              <HelpCircle class="w-3 h-3" /> Esqueceu a senha?
            </button>
          </div>
        </div>

        <button 
          type="submit" 
          :disabled="isLoading"
          class="w-full py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-blue-400 text-white font-bold rounded-lg transition-transform transform active:scale-95 shadow-lg flex justify-center items-center gap-2"
        >
          <Loader2 v-if="isLoading" class="w-5 h-5 animate-spin" />
          <span v-else>Entrar no Sistema</span>
        </button>

        <p v-if="error" class="text-sm font-semibold text-red-500 text-center animate-pulse">
          {{ error }}
        </p>
      </form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'
import { Snowflake, Lock, User, ArrowLeft, HelpCircle, Loader2 } from 'lucide-vue-next'

const router = useRouter()
const authStore = useAuthStore()

const identifier = ref('admin')
const password = ref('1234')
const isLoading = ref(false)
const error = ref('')

const handleLogin = async () => {
  error.value = ''
  isLoading.value = true
  
  try {
    await authStore.login(identifier.value, password.value)
    alert(`Bem-vindo, ${authStore.user?.username}!`)
    router.push('/dashboard')
  } catch (err: any) {
    error.value = err.message
  } finally {
    isLoading.value = false
  }
}

const handleForgot = () => {
  alert('Por favor, entre em contato com o administrador do sistema para redefinir sua senha.')
}
</script>
