// src/components/FinanceTab.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { Landmark, ArrowUpCircle, ArrowDownCircle, History, PlusCircle, X, Search, FileText } from 'lucide-vue-next'
import { useFinanceStore } from '../stores/finances'
import CurrencyInput from './CurrencyInput.vue'

const financeStore = useFinanceStore()

const isNewTrxModalOpen = ref(false)
const filterQuery = ref('')

const OFFICIAL_CATEGORIES = ["Orçamento", "Fixo", "Variável", "Serviço", "Venda", "Outros"]

const form = ref<{
  type: 'receita' | 'despesa'
  description: string
  category: string
  amount: number
}>({
  type: 'receita',
  description: '',
  category: 'Orçamento',
  amount: 0
})

onMounted(async () => {
  await financeStore.loadFinances()
})

const save = async () => {
  if (!form.value.description || form.value.amount <= 0) return
  await financeStore.createTransaction({ ...form.value })
  isNewTrxModalOpen.value = false
  form.value = { type: 'receita', description: '', category: 'Orçamento', amount: 0 }
}

const filteredTransactions = computed(() => {
  if (!filterQuery.value) return financeStore.transactions
  return financeStore.transactions.filter(t => 
    t.description.toLowerCase().includes(filterQuery.value.toLowerCase()) ||
    t.category.toLowerCase().includes(filterQuery.value.toLowerCase())
  )
})
</script>

<template>
  <div class="space-y-4 sm:space-y-6 animate-in fade-in duration-500">
    <!-- Header Principal -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
      <div>
        <h2 class="text-3xl font-black text-blue-900 dark:text-white">Central Financeira</h2>
        <p class="text-xs text-gray-500 mt-1">Gestão integrada do Fluxo de Caixa da Lider</p>
      </div>
    </div>

    <!-- ======================= -->
    <!-- FLUXO DE CAIXA         -->
    <!-- ======================= -->
    <div class="space-y-8 mt-2 animate-in fade-in duration-500">
      
      <!-- Controles Fluxo de caixa -->
      <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <h3 class="text-xl font-black text-blue-900 dark:text-white">Indicadores Gerais</h3>
        <button @click="isNewTrxModalOpen = true" class="flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-2xl text-sm font-black shadow-lg shadow-blue-500/30 transition-all hover:scale-105 active:scale-95">
          <PlusCircle class="w-5 h-5" /> Novo Lançamento
        </button>
      </div>

      <!-- Cards Superiores Premium -->
      <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div class="bg-gradient-to-br from-blue-700 to-blue-900 text-white shadow-2xl rounded-[32px] p-8 relative overflow-hidden h-52 flex flex-col justify-between group border border-blue-400/20">
          <Landmark class="absolute right-[-40px] top-[-40px] w-64 h-64 opacity-10 group-hover:rotate-12 transition-transform duration-1000" />
          <div>
            <p class="text-[10px] font-black uppercase tracking-widest text-blue-200 opacity-80 pl-1">Saldo em Conta</p>
            <p class="text-3xl lg:text-5xl font-black mt-2 tracking-tighter truncate">R$ {{ financeStore.saldo.toLocaleString('pt-BR', { minimumFractionDigits: 2 }) }}</p>
          </div>
          <div class="flex items-center gap-2">
             <div class="bg-white/10 backdrop-blur-md px-4 py-2 rounded-xl text-[10px] font-black uppercase border border-white/10 shrink-0">Tesouraria Lider</div>
             <div class="h-2 w-2 rounded-full bg-green-400 animate-pulse shrink-0"></div>
          </div>
        </div>
        
        <div class="bg-white dark:bg-slate-900 border border-blue-50 dark:border-slate-800 rounded-[32px] shadow-xl p-6 lg:p-8 flex flex-col justify-between h-52 border-l-[12px] border-l-green-500 transition-all hover:-translate-y-1">
          <div>
             <div class="flex items-center gap-2 text-green-600 dark:text-green-400">
               <ArrowUpCircle class="w-5 h-5" />
               <h3 class="text-xs font-black uppercase tracking-widest">Total de Receitas</h3>
             </div>
             <p class="text-2xl lg:text-4xl font-black text-slate-800 dark:text-white mt-4 tracking-tighter truncate">
                R$ {{ financeStore.totalReceitas.toLocaleString('pt-BR', { minimumFractionDigits: 2 }) }}
             </p>
          </div>
          <p class="text-[10px] text-gray-400 font-bold uppercase tracking-tight">Sincronizado com Ordens de Serviço</p>
        </div>

        <div class="bg-white dark:bg-slate-900 border border-blue-50 dark:border-slate-800 rounded-[32px] shadow-xl p-6 lg:p-8 flex flex-col justify-between h-52 border-l-[12px] border-l-red-500 transition-all hover:-translate-y-1">
          <div>
             <div class="flex items-center gap-2 text-red-600 dark:text-red-400">
               <ArrowDownCircle class="w-5 h-5" />
               <h3 class="text-xs font-black uppercase tracking-widest">Total de Despesas</h3>
             </div>
             <p class="text-2xl lg:text-4xl font-black text-slate-800 dark:text-white mt-4 tracking-tighter truncate">
                R$ {{ financeStore.totalDespesas.toLocaleString('pt-BR', { minimumFractionDigits: 2 }) }}
             </p>
          </div>
          <p class="text-[10px] text-gray-400 font-bold uppercase tracking-tight">Pagamentos de Peças e Operações</p>
        </div>
      </div>

      <!-- Filtros e Tabela Analítica -->
      <div class="bg-white dark:bg-slate-900 border border-blue-50 dark:border-slate-800 rounded-[32px] shadow-2xl overflow-hidden">
        <div class="px-8 py-8 border-b border-gray-100 dark:border-slate-800 flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div>
            <h3 class="text-xl font-black text-blue-900 dark:text-white flex items-center gap-3">
              <History class="w-7 h-7 text-blue-600" /> Fluxo de Lançamentos
            </h3>
            <p class="text-xs text-gray-400 mt-1">Lista cronológica de todas as entradas e saídas</p>
          </div>
          <div class="relative max-w-sm w-full">
            <Search class="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" :size="20" />
            <input v-model="filterQuery" type="text" placeholder="Buscar por descrição..." class="w-full pl-12 pr-6 py-4 rounded-[20px] bg-gray-50 dark:bg-slate-950 border-none focus:ring-2 focus:ring-blue-600 outline-none text-sm dark:text-white font-medium shadow-inner" />
          </div>
        </div>
        
        <div class="overflow-x-auto">
          <table class="w-full text-left border-collapse">
            <thead>
              <tr class="bg-gray-50 dark:bg-slate-800/50 border-b dark:border-slate-700 text-[10px] uppercase font-black text-gray-500 tracking-widest">
                <th class="px-8 py-4">Data</th>
                <th class="px-8 py-4">Descrição do Movimento</th>
                <th class="px-8 py-4">Categoria</th>
                <th class="px-8 py-4 text-right">Valor Líquido (R$)</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-100 dark:divide-slate-800">
              <tr v-for="trx in filteredTransactions" :key="trx.id" class="hover:bg-blue-50/20 dark:hover:bg-slate-800/30 transition-all duration-300 group">
                <td class="px-8 py-6 text-gray-400 text-xs font-black uppercase whitespace-nowrap">{{ new Date(trx.date).toLocaleDateString() }}</td>
                <td class="px-8 py-6">
                  <div class="flex flex-col">
                    <span class="font-black text-slate-800 dark:text-gray-100 text-base min-w-[200px]">{{ trx.description }}</span>
                    <span class="flex items-center gap-1.5 text-[10px] font-black uppercase mt-1" :class="trx.type === 'receita' ? 'text-green-600' : 'text-red-500'">
                      <component :is="trx.type === 'receita' ? ArrowUpCircle : ArrowDownCircle" :size="12" />
                      Lançamento de {{ trx.type }}
                    </span>
                  </div>
                </td>
                <td class="px-8 py-6">
                  <div class="inline-flex items-center px-4 py-1.5 bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 rounded-xl text-[10px] font-black uppercase border border-gray-200 dark:border-slate-700 shadow-sm whitespace-nowrap">
                    {{ trx.category }}
                  </div>
                </td>
                <td class="px-8 py-6 text-right whitespace-nowrap">
                  <div class="flex flex-col items-end">
                    <span class="font-black text-xl tracking-tighter" :class="trx.type === 'receita' ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'">
                      {{ trx.type === 'receita' ? '+' : '-' }} R$ {{ trx.amount.toLocaleString('pt-BR', { minimumFractionDigits: 2 }) }}
                    </span>
                    <span class="text-[9px] font-bold text-gray-400 uppercase mt-1">Efetivado com sucesso</span>
                  </div>
                </td>
              </tr>
              <tr v-if="filteredTransactions.length === 0">
                <td colspan="4" class="px-8 py-24 text-center">
                  <div class="flex flex-col items-center opacity-30">
                    <History :size="48" class="text-gray-400 mb-4" />
                    <p class="font-black uppercase tracking-[0.2em] text-sm">Nenhum registro encontrado</p>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>


    <!-- Modal Novo Lançamento -->
    <div v-if="isNewTrxModalOpen" class="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-md animate-in fade-in duration-300">
      <div class="bg-white dark:bg-slate-900 rounded-[40px] w-full max-w-lg shadow-2xl overflow-hidden border border-white/20 dark:border-slate-800 animate-in zoom-in-95 scale-100">
        <div class="px-10 py-8 bg-blue-50/50 dark:bg-slate-800/50 border-b border-gray-100 dark:border-slate-800 flex justify-between items-center">
            <div>
              <h3 class="text-2xl font-black text-blue-900 dark:text-white tracking-tight">Novo Movimento</h3>
              <p class="text-xs text-gray-500 font-bold mt-1 uppercase tracking-wider">Tesouraria Lider Refrigeração</p>
            </div>
            <button @click="isNewTrxModalOpen = false" class="p-3 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-2xl text-gray-400 hover:text-red-500 transition-all">
              <X class="w-6 h-6"/>
            </button>
        </div>
        
        <div class="p-10 space-y-8">
          <div class="grid grid-cols-2 gap-6">
            <button @click="form.type = 'receita'" 
              :class="form.type === 'receita' ? 'bg-green-600 text-white shadow-xl shadow-green-500/30 scale-105' : 'bg-gray-50 dark:bg-slate-800 text-gray-400 opacity-50'" 
              class="rounded-3xl py-5 font-black flex flex-col items-center gap-2 transition-all border border-gray-100 dark:border-slate-800">
              <ArrowUpCircle class="w-6 h-6"/> 
              <span class="text-xs uppercase tracking-widest">Receita</span>
            </button>
            <button @click="form.type = 'despesa'" 
              :class="form.type === 'despesa' ? 'bg-red-600 text-white shadow-xl shadow-red-500/30 scale-105' : 'bg-gray-50 dark:bg-slate-800 text-gray-400 opacity-50'" 
              class="rounded-3xl py-5 font-black flex flex-col items-center gap-2 transition-all border border-gray-100 dark:border-slate-800">
              <ArrowDownCircle class="w-6 h-6"/> 
              <span class="text-xs uppercase tracking-widest">Despesa</span>
            </button>
          </div>

          <div class="space-y-6">
            <div class="space-y-2">
              <label class="text-[10px] font-black uppercase text-gray-400 tracking-[0.2em] pl-1">Descrição do Lançamento</label>
              <input v-model="form.description" type="text" placeholder="Ex: Pagamento Fornecedor" class="w-full px-6 py-5 rounded-2xl border border-gray-100 dark:border-slate-800 bg-gray-50 dark:bg-slate-950 dark:text-white focus:ring-4 focus:ring-blue-100 dark:focus:ring-blue-900/20 outline-none font-bold text-lg transition-all" />
            </div>
            
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
               <div class="space-y-2">
                 <label class="text-[10px] font-black uppercase text-gray-400 tracking-[0.2em] pl-1">Categoria</label>
                 <select v-model="form.category" class="w-full px-6 py-5 rounded-2xl border border-gray-100 dark:border-slate-800 bg-gray-50 dark:bg-slate-950 dark:text-white focus:ring-2 focus:ring-blue-600 outline-none font-black appearance-none">
                   <option v-for="cat in OFFICIAL_CATEGORIES" :key="cat" :value="cat">{{ cat }}</option>
                 </select>
               </div>
               <div class="space-y-2">
                 <label class="text-[10px] font-black uppercase text-gray-400 tracking-[0.2em] pl-1">Valor do Título (R$)</label>
                 <CurrencyInput v-model="form.amount" class="w-full px-6 py-5 rounded-2xl border border-gray-100 dark:border-slate-800 bg-gray-50 dark:bg-slate-950 dark:text-white focus:ring-2 focus:ring-blue-600 outline-none font-black text-lg" />
               </div>
            </div>
          </div>
        </div>

        <div class="px-10 py-8 bg-gray-50 dark:bg-slate-800/50 flex flex-col md:flex-row justify-end gap-4 border-t border-gray-100 dark:border-slate-800">
          <button @click="isNewTrxModalOpen = false" class="px-8 py-4 font-black text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition-colors uppercase text-xs tracking-widest leading-none">Cancelar Registro</button>
          <button @click="save" :disabled="!form.description || form.amount <= 0" class="px-10 py-4 font-black text-white bg-blue-600 hover:bg-blue-700 disabled:bg-blue-300 rounded-2xl shadow-2xl shadow-blue-500/40 flex items-center justify-center gap-3 transition-all hover:scale-105 active:scale-95 leading-none">
            <PlusCircle :size="18" /> Confirmar Lançamento
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/FinanceTab.tsx
"use client";

import React from 'react';
import { 
  TrendingUp, TrendingDown, DollarSign, Receipt, Plus, Trash2, 
  AlertCircle, Wallet, PieChart, Calendar, ArrowUpRight, ArrowDownRight,
  Percent, CheckCircle2, Clock, Edit2, Save, X, FileText, Ban, Landmark
} from 'lucide-react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { showSuccess, showError } from '@/utils/toast';

interface Transaction {
  id: string;
  description: string;
  value: number;
  category: string;
  date: string;
  type: 'Entrada' | 'Saída';
  status: 'Pendente' | 'Concluído';
  paymentDate?: string;
}

interface FinanceTabProps {
  orders: any[];
}

const FinanceTab = ({ orders }: FinanceTabProps) => {
  const [transactions, setTransactions] = React.useState<Transaction[]>([]);
  const [formType, setFormType] = React.useState<'Entrada' | 'Saída'>('Saída');
  const [editingTransaction, setEditingTransaction] = React.useState<Transaction | null>(null);
  const [isEditModalOpen, setIsEditModalOpen] = React.useState(false);
  
  const [newTransaction, setNewTransaction] = React.useState({
    description: '',
    value: '',
    category: 'Fixo',
    date: new Date().toISOString().split('T')[0],
    status: 'Pendente' as const
  });

  React.useEffect(() => {
    const saved = localStorage.getItem('lider_transactions');
    if (saved) setTransactions(JSON.parse(saved));
  }, []);

  const saveTransactions = (updated: Transaction[]) => {
    setTransactions(updated);
    localStorage.setItem('lider_transactions', JSON.stringify(updated));
  };

  const handleAddTransaction = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTransaction.description || !newTransaction.value) {
      showError('Preencha a descrição e o valor.');
      return;
    }

    const transaction: Transaction = {
      id: Math.random().toString(36).substr(2, 9),
      description: newTransaction.description,
      value: Number(newTransaction.value),
      category: newTransaction.category,
      date: newTransaction.date,
      type: formType,
      status: 'Pendente'
    };

    saveTransactions([transaction, ...transactions]);
    setNewTransaction({ ...newTransaction, description: '', value: '' });
    showSuccess(`${formType} registrada com sucesso!`);
  };

  const toggleStatus = (id: string) => {
    const updated = transactions.map(t => {
      if (t.id === id) {
        const newStatus = t.status === 'Pendente' ? 'Concluído' : 'Pendente';
        return { 
          ...t, 
          status: newStatus,
          paymentDate: newStatus === 'Concluído' ? new Date().toLocaleDateString() : undefined
        };
      }
      return t;
    });
    saveTransactions(updated);
    showSuccess('Status atualizado!');
  };

  const deleteTransaction = (id: string) => {
    if (window.confirm('Excluir este lançamento permanentemente?')) {
      saveTransactions(transactions.filter(t => t.id !== id));
    }
  };

  const handleEditClick = (transaction: Transaction) => {
    setEditingTransaction({ ...transaction });
    setIsEditModalOpen(true);
  };

  const handleSaveEdit = () => {
    if (!editingTransaction) return;
    const updated = transactions.map(t => t.id === editingTransaction.id ? editingTransaction : t);
    saveTransactions(updated);
    setIsEditModalOpen(false);
    showSuccess('Lançamento atualizado!');
  };

  // Cálculos para Gestão de Gastos (Fluxo de Caixa)
  const revenueFromOrders = orders
    .filter(o => o.status === 'Executado')
    .reduce((acc, o) => acc + o.total, 0);

  const manualEntradas = transactions
    .filter(t => t.type === 'Entrada' && t.status === 'Concluído')
    .reduce((acc, t) => acc + t.value, 0);

  const totalEntradasGeral = revenueFromOrders + manualEntradas;

  const manualSaidasPagas = transactions
    .filter(t => t.type === 'Saída' && t.status === 'Concluído')
    .reduce((acc, t) => acc + t.value, 0);

  const manualSaidasPendentes = transactions
    .filter(t => t.type === 'Saída' && t.status === 'Pendente')
    .reduce((acc, t) => acc + t.value, 0);

  const saldoCaixa = totalEntradasGeral - manualSaidasPagas;

  // Cálculos para Status de Orçamentos
  const totalExecutado = orders.filter(o => o.status === 'Executado').reduce((acc, o) => acc + o.total, 0);
  const totalPendente = orders.filter(o => o.status === 'Pendente').reduce((acc, o) => acc + o.total, 0);
  const totalCancelado = orders.filter(o => o.status === 'Cancelado').reduce((acc, o) => acc + o.total, 0);

  return (
    <div className="space-y-8">
      <Tabs defaultValue="gastos" className="w-full">
        <TabsList className="bg-white dark:bg-slate-900 border border-blue-100 dark:border-slate-800 mb-6 w-full justify-start overflow-x-auto flex-nowrap scrollbar-hide">
          <TabsTrigger value="gastos" className="flex-shrink-0">Gestão de Gastos</TabsTrigger>
          <TabsTrigger value="orcamentos" className="flex-shrink-0">Status de Orçamentos</TabsTrigger>
        </TabsList>

        <TabsContent value="gastos" className="space-y-8">
          {/* Cards Específicos de Gastos */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <FinanceCard 
              title="Entradas Totais" 
              value={totalEntradasGeral} 
              icon={<ArrowUpRight className="text-green-500" />} 
              color="border-green-100 bg-green-50/30"
              subtitle="OS Executadas + Manuais"
            />
            <FinanceCard 
              title="Saídas (Pagas)" 
              value={manualSaidasPagas} 
              icon={<CheckCircle2 className="text-blue-500" />} 
              color="border-blue-100 bg-blue-50/30"
              subtitle="Despesas liquidadas"
            />
            <FinanceCard 
              title="Saídas (Pendentes)" 
              value={manualSaidasPendentes} 
              icon={<Clock className="text-red-500" />} 
              color="border-red-100 bg-red-50/30"
              subtitle="Contas a pagar"
            />
            <FinanceCard 
              title="Saldo em Caixa" 
              value={saldoCaixa} 
              icon={<Wallet className={saldoCaixa >= 0 ? "text-green-600" : "text-red-600"} />} 
              color={saldoCaixa >= 0 ? "border-green-100 bg-green-50/30" : "border-red-200 bg-red-50"}
              subtitle="Entradas - Saídas Pagas"
            />
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Lançamento Financeiro */}
            <Card className="h-fit shadow-lg border-blue-100 dark:border-slate-800 dark:bg-slate-900">
              <CardHeader className="bg-blue-50/50 dark:bg-slate-800/50 border-b border-blue-50 dark:border-slate-800">
                <div className="flex flex-col gap-4">
                  <CardTitle className="text-lg flex items-center gap-2 text-blue-900 dark:text-white">
                    <Receipt className="text-blue-600" /> Novo Lançamento
                  </CardTitle>
                  <div className="flex p-1 bg-gray-100 dark:bg-slate-800 rounded-xl">
                    <button 
                      onClick={() => setFormType('Entrada')}
                      className={`flex-1 py-2 text-xs font-black uppercase rounded-lg transition-all flex items-center justify-center gap-2 ${
                        formType === 'Entrada' 
                          ? 'bg-green-500 text-white shadow-lg' 
                          : 'text-gray-500 hover:text-gray-700 dark:hover:text-gray-300'
                      }`}
                    >
                      <ArrowUpRight size={14} /> Entrada
                    </button>
                    <button 
                      onClick={() => setFormType('Saída')}
                      className={`flex-1 py-2 text-xs font-black uppercase rounded-lg transition-all flex items-center justify-center gap-2 ${
                        formType === 'Saída' 
                          ? 'bg-red-500 text-white shadow-lg' 
                          : 'text-gray-500 hover:text-gray-700 dark:hover:text-gray-300'
                      }`}
                    >
                      <ArrowDownRight size={14} /> Saída
                    </button>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="pt-6">
                <form onSubmit={handleAddTransaction} className="space-y-4">
                  <div className="space-y-1">
                    <label className="text-[10px] font-black text-gray-400 uppercase">Descrição</label>
                    <Input 
                      placeholder={formType === 'Entrada' ? "Ex: Venda de Peça Avulsa, Aporte..." : "Ex: Aluguel, Luz, Peças..."}
                      value={newTransaction.description}
                      onChange={e => setNewTransaction({...newTransaction, description: e.target.value})}
                      className="dark:bg-slate-950 dark:border-slate-800"
                    />
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-1">
                      <label className="text-[10px] font-black text-gray-400 uppercase">Valor (R$)</label>
                      <Input 
                        type="number" 
                        placeholder="0.00" 
                        value={newTransaction.value}
                        onChange={e => setNewTransaction({...newTransaction, value: e.target.value})}
                        className="dark:bg-slate-950 dark:border-slate-800"
                      />
                    </div>
                    <div className="space-y-1">
                      <label className="text-[10px] font-black text-gray-400 uppercase">Categoria</label>
                      <Select value={newTransaction.category} onValueChange={v => setNewTransaction({...newTransaction, category: v})}>
                        <SelectTrigger className="dark:bg-slate-950 dark:border-slate-800"><SelectValue /></SelectTrigger>
                        <SelectContent>
                          <SelectItem value="Fixo">Fixo</SelectItem>
                          <SelectItem value="Variável">Variável</SelectItem>
                          <SelectItem value="Serviço">Serviço</SelectItem>
                          <SelectItem value="Venda">Venda</SelectItem>
                          <SelectItem value="Piedade">Piedade</SelectItem>
                          <SelectItem value="Outros">Outros</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                  <div className="space-y-1">
                    <label className="text-[10px] font-black text-gray-400 uppercase">Data</label>
                    <Input 
                      type="date" 
                      value={newTransaction.date}
                      onChange={e => setNewTransaction({...newTransaction, date: e.target.value})}
                      className="dark:bg-slate-950 dark:border-slate-800"
                    />
                  </div>
                  <Button 
                    type="submit" 
                    className={`w-full py-6 font-bold transition-colors ${
                      formType === 'Entrada' ? 'bg-green-600 hover:bg-green-700' : 'bg-blue-600 hover:bg-blue-700'
                    }`}
                  >
                    <Plus className="mr-2 h-4 w-4" /> Lançar {formType}
                  </Button>
                </form>
              </CardContent>
            </Card>

            {/* Tabela de Lançamentos */}
            <Card className="lg:col-span-2 shadow-lg border-blue-50 dark:border-slate-800 dark:bg-slate-900">
              <CardHeader className="bg-blue-50/50 dark:bg-slate-800/50 border-b border-blue-50 dark:border-slate-800">
                <CardTitle className="text-lg flex items-center gap-2 text-blue-900 dark:text-white">
                  <PieChart className="text-blue-600" /> Gestão de Fluxo de Caixa
                </CardTitle>
              </CardHeader>
              <CardContent className="p-0">
                <div className="overflow-x-auto">
                  <Table>
                    <TableHeader>
                      <TableRow className="bg-gray-50/50 dark:bg-slate-800/30">
                        <TableHead className="font-bold">Data</TableHead>
                        <TableHead className="font-bold">Descrição</TableHead>
                        <TableHead className="font-bold">Status</TableHead>
                        <TableHead className="text-right font-bold">Valor</TableHead>
                        <TableHead className="text-right font-bold">Ações</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {transactions.map((t) => (
                        <TableRow key={t.id} className={`hover:bg-gray-50/50 dark:hover:bg-slate-800/30 ${t.status === 'Concluído' ? 'opacity-70' : ''}`}>
                          <TableCell className="text-xs text-gray-500 dark:text-gray-400">{t.date.split('-').reverse().join('/')}</TableCell>
                          <TableCell>
                            <div className="flex flex-col">
                              <div className="flex items-center gap-2">
                                {t.type === 'Entrada' ? <ArrowUpRight size={12} className="text-green-500" /> : <ArrowDownRight size={12} className="text-red-500" />}
                                <span className="font-bold dark:text-gray-300">{t.description}</span>
                              </div>
                              <span className="text-[10px] text-gray-400 uppercase ml-5">{t.category}</span>
                            </div>
                          </TableCell>
                          <TableCell>
                            <button 
                              onClick={() => toggleStatus(t.id)}
                              className={`flex items-center gap-1.5 px-3 py-1 rounded-full text-[10px] font-black uppercase transition-all ${
                                t.status === 'Concluído' 
                                  ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' 
                                  : 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400 animate-pulse'
                              }`}
                            >
                              {t.status === 'Concluído' ? <CheckCircle2 size={12} /> : <Clock size={12} />}
                              {t.status === 'Concluído' ? (t.type === 'Entrada' ? 'Recebido' : 'Pago') : 'Pendente'}
                            </button>
                          </TableCell>
                          <TableCell className={`text-right font-bold ${t.type === 'Entrada' ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'}`}>
                            {t.type === 'Entrada' ? '+' : '-'} R$ {t.value.toFixed(2)}
                          </TableCell>
                          <TableCell className="text-right">
                            <div className="flex justify-end gap-1">
                              <Button variant="ghost" size="sm" className="text-blue-600 dark:text-blue-400" onClick={() => handleEditClick(t)}>
                                <Edit2 size={14} />
                              </Button>
                              <Button variant="ghost" size="sm" className="text-red-500" onClick={() => deleteTransaction(t.id)}>
                                <Trash2 size={14} />
                              </Button>
                            </div>
                          </TableCell>
                        </TableRow>
                      ))}
                      {transactions.length === 0 && (
                        <TableRow>
                          <TableCell colSpan={5} className="text-center py-8 text-gray-500">Nenhum lançamento manual registrado.</TableCell>
                        </TableRow>
                      )}
                    </TableBody>
                  </Table>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="orcamentos" className="space-y-8">
          {/* Cards Específicos de Orçamentos */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <FinanceCard 
              title="Receita (Executado)" 
              value={totalExecutado} 
              icon={<CheckCircle2 className="text-green-500" />} 
              color="border-green-100 bg-green-50/30"
              subtitle="Serviços concluídos"
            />
            <FinanceCard 
              title="Previsão (Pendente)" 
              value={totalPendente} 
              icon={<Clock className="text-yellow-500" />} 
              color="border-yellow-100 bg-yellow-50/30"
              subtitle="Orçamentos em aberto"
            />
            <FinanceCard 
              title="Perda (Cancelado)" 
              value={totalCancelado} 
              icon={<Ban className="text-red-500" />} 
              color="border-red-100 bg-red-50/30"
              subtitle="Serviços não realizados"
            />
          </div>

          <Card className="shadow-lg border-blue-50 dark:border-slate-800 dark:bg-slate-900">
            <CardHeader className="bg-blue-50/50 dark:bg-slate-800/50 border-b border-blue-50 dark:border-slate-800">
              <CardTitle className="text-lg flex items-center gap-2 text-blue-900 dark:text-white">
                <FileText className="text-blue-600" /> Impacto Financeiro por Orçamento
              </CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow className="bg-gray-50/50 dark:bg-slate-800/30">
                      <TableHead className="font-bold">ID</TableHead>
                      <TableHead className="font-bold">Cliente</TableHead>
                      <TableHead className="font-bold">Data</TableHead>
                      <TableHead className="font-bold">Status</TableHead>
                      <TableHead className="text-right font-bold">Valor Total</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {orders.map((order) => (
                      <TableRow key={order.id} className="hover:bg-gray-50/50 dark:hover:bg-slate-800/30">
                        <TableCell className="font-bold text-blue-600 dark:text-blue-400">#{order.id}</TableCell>
                        <TableCell className="dark:text-gray-300">{order.clientName}</TableCell>
                        <TableCell className="text-xs text-gray-500 dark:text-gray-400">{order.date}</TableCell>
                        <TableCell>
                          <span className={`flex items-center gap-1.5 px-3 py-1 rounded-full text-[10px] font-black uppercase w-fit ${
                            order.status === 'Executado' ? 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400' : 
                            order.status === 'Pendente' ? 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400' : 
                            'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400'
                          }`}>
                            {order.status === 'Executado' ? <CheckCircle2 size={12} /> : order.status === 'Pendente' ? <Clock size={12} /> : <Ban size={12} />}
                            {order.status}
                          </span>
                        </TableCell>
                        <TableCell className="text-right font-bold dark:text-gray-300">
                          R$ {order.total.toFixed(2)}
                        </TableCell>
                      </TableRow>
                    ))}
                    {orders.length === 0 && (
                      <TableRow>
                        <TableCell colSpan={5} className="text-center py-8 text-gray-500">Nenhum orçamento encontrado.</TableCell>
                      </TableRow>
                    )}
                  </TableBody>
                </Table>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Modal de Edição */}
      <Dialog open={isEditModalOpen} onOpenChange={setIsEditModalOpen}>
        <DialogContent className="sm:max-w-[425px] dark:bg-slate-900 dark:border-slate-800">
          <DialogHeader>
            <DialogTitle className="text-blue-900 dark:text-white">Editar Lançamento</DialogTitle>
          </DialogHeader>
          {editingTransaction && (
            <div className="grid gap-4 py-4">
              <div className="grid gap-2">
                <label className="text-xs font-bold text-gray-400 uppercase">Descrição</label>
                <Input 
                  value={editingTransaction.description} 
                  onChange={(e) => setEditingTransaction({...editingTransaction, description: e.target.value})} 
                  className="dark:bg-slate-950 dark:border-slate-800"
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="grid gap-2">
                  <label className="text-xs font-bold text-gray-400 uppercase">Valor (R$)</label>
                  <Input 
                    type="number"
                    value={editingTransaction.value} 
                    onChange={(e) => setEditingTransaction({...editingTransaction, value: Number(e.target.value)})} 
                    className="dark:bg-slate-950 dark:border-slate-800"
                  />
                </div>
                <div className="grid gap-2">
                  <label className="text-xs font-bold text-gray-400 uppercase">Categoria</label>
                  <Select value={editingTransaction.category} onValueChange={v => setEditingTransaction({...editingTransaction, category: v})}>
                    <SelectTrigger className="dark:bg-slate-950 dark:border-slate-800"><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Fixo">Fixo</SelectItem>
                      <SelectItem value="Variável">Variável</SelectItem>
                      <SelectItem value="Serviço">Serviço</SelectItem>
                      <SelectItem value="Venda">Venda</SelectItem>
                      <SelectItem value="Piedade">Piedade</SelectItem>
                      <SelectItem value="Outros">Outros</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="grid gap-2">
                <label className="text-xs font-bold text-gray-400 uppercase">Data</label>
                <Input 
                  type="date"
                  value={editingTransaction.date} 
                  onChange={(e) => setEditingTransaction({...editingTransaction, date: e.target.value})} 
                  className="dark:bg-slate-950 dark:border-slate-800"
                />
              </div>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsEditModalOpen(false)} className="dark:border-slate-800">Cancelar</Button>
            <Button className="bg-blue-600" onClick={handleSaveEdit}>Salvar Alterações</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

const FinanceCard = ({ title, value, icon, color, subtitle }: { title: string, value: number, icon: React.ReactNode, color: string, subtitle: string }) => (
  <Card className={`border shadow-sm ${color}`}>
    <CardContent className="p-6">
      <div className="flex items-center justify-between mb-4">
        <p className="text-[10px] font-black text-gray-500 dark:text-gray-400 uppercase tracking-widest">{title}</p>
        <div className="bg-white dark:bg-slate-800 p-2 rounded-lg shadow-sm">
          {icon}
        </div>
      </div>
      <p className={`text-2xl font-black ${value < 0 ? 'text-red-600' : 'text-blue-900 dark:text-white'}`}>
        R$ {value.toFixed(2)}
      </p>
      <p className="text-[10px] text-gray-400 mt-1 font-medium">{subtitle}</p>
    </CardContent>
  </Card>
);

export default FinanceTab;
