// src/components/Navbar.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { Snowflake, Menu, X } from 'lucide-vue-next'
import ThemeToggle from './ThemeToggle.vue'

const isMenuOpen = ref(false)
const isScrolled = ref(false)

const handleScroll = () => {
  isScrolled.value = window.scrollY > 20
}

onMounted(() => {
  window.addEventListener('scroll', handleScroll)
})

onUnmounted(() => {
  window.removeEventListener('scroll', handleScroll)
})

const navLinks = [
  { name: 'Serviços', href: '#servicos' },
  { name: 'Sobre Nós', href: '#sobre' },
  { name: 'Contato', href: '#contato' }
]
</script>

<template>
  <nav 
    :class="[
      'fixed top-0 left-0 w-full z-50 transition-all duration-300',
      isScrolled ? 'bg-mesh-gradient shadow-2xl py-3' : 'bg-transparent py-6'
    ]"
  >
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-between items-center">
        <!-- Logo -->
        <div class="flex items-center">
          <router-link to="/" class="flex items-center gap-2 group">
            <div class="bg-blue-600 p-2 rounded-xl group-hover:rotate-180 transition-transform duration-700 shadow-lg shadow-blue-500/30">
              <Snowflake class="h-6 w-6 text-white" />
            </div>
            <div class="flex flex-col">
              <span :class="['text-xl font-black leading-none tracking-tight transition-colors', isScrolled ? 'text-white' : 'text-blue-900 dark:text-white']">LIDER REFRIGERAÇÃO</span>
              <span :class="['text-[8px] uppercase tracking-[0.3em] font-black mt-0.5 transition-colors', isScrolled ? 'text-blue-200' : 'text-blue-500']">Excelência Térmica</span>
            </div>
          </router-link>
        </div>
        
        <!-- Desktop Menu -->
        <div class="hidden md:flex items-center space-x-10">
          <a 
            v-for="link in navLinks" 
            :key="link.name" 
            :href="link.href" 
            :class="['text-sm font-black uppercase tracking-widest transition-colors', isScrolled ? 'text-blue-100/80 hover:text-white' : 'text-gray-500 hover:text-blue-600 dark:text-gray-300 dark:hover:text-blue-400']"
          >
            {{ link.name }}
          </a>
          
          <ThemeToggle />
        </div>

        <!-- Mobile Toggle -->
        <div class="md:hidden flex items-center gap-4">
          <ThemeToggle />
          <button 
            @click="isMenuOpen = !isMenuOpen" 
            class="p-2 text-blue-900 dark:text-white bg-white/50 dark:bg-slate-800/50 rounded-xl"
          >
            <component :is="isMenuOpen ? X : Menu" :size="24" />
          </button>
        </div>
      </div>
    </div>

    <!-- Mobile Menu -->
    <Transition 
      enter-active-class="animate-in slide-in-from-top duration-300" 
      leave-active-class="animate-out slide-out-to-top duration-300"
    >
      <div 
        v-if="isMenuOpen" 
        class="md:hidden absolute top-full left-0 w-full bg-white dark:bg-slate-900 border-b border-gray-100 dark:border-slate-800 p-4 space-y-4 shadow-2xl"
      >
        <a 
          v-for="link in navLinks" 
          :key="link.name" 
          :href="link.href" 
          @click="isMenuOpen = false" 
          class="block px-4 py-3 text-sm font-black text-gray-500 dark:text-gray-300 uppercase tracking-widest hover:bg-blue-50 dark:hover:bg-slate-800 rounded-xl transition-all"
        >
          {{ link.name }}
        </a>
        <router-link 
          to="/login" 
          class="block px-4 py-4 text-center bg-blue-600 text-white rounded-xl font-black uppercase text-xs"
        >
          Área de Gestão
        </router-link>
      </div>
    </Transition>
  </nav>
</template>

// src/components/Navbar.tsx
"use client";

import React from 'react';
import { Snowflake, Menu, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { ThemeToggle } from './ThemeToggle';

const Navbar = () => {
  const [isOpen, setIsOpen] = React.useState(false);

  return (
    <nav className="bg-white dark:bg-slate-950 border-b border-blue-100 dark:border-slate-800 sticky top-0 z-50 transition-colors">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between h-20">
          <div className="flex items-center">
            <Link to="/" className="flex items-center gap-2">
              <Snowflake className="h-8 w-8 text-blue-600" />
              <div>
                <span className="text-xl font-bold text-blue-900 dark:text-white block leading-none">LIDER REFRIGERAÇÃO</span>
                <span className="text-[10px] text-blue-500 uppercase tracking-widest font-medium">Manutenção Preventiva e Corretiva</span>
              </div>
            </Link>
          </div>
          
          <div className="hidden md:flex items-center space-x-8">
            <a href="#servicos" className="text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 font-medium transition-colors">Serviços</a>
            <a href="#sobre" className="text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 font-medium transition-colors">Sobre Nós</a>
            <a href="#contato" className="text-gray-600 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 font-medium transition-colors">Contato</a>
            <ThemeToggle />
          </div>

          <div className="md:hidden flex items-center gap-4">
            <ThemeToggle />
            <button onClick={() => setIsOpen(!isOpen)} className="text-blue-900 dark:text-white">
              {isOpen ? <X size={28} /> : <Menu size={28} />}
            </button>
          </div>
        </div>
      </div>

      {/* Mobile Menu */}
      {isOpen && (
        <div className="md:hidden bg-white dark:bg-slate-950 border-b border-blue-50 dark:border-slate-800 p-4 space-y-4">
          <a href="#servicos" onClick={() => setIsOpen(false)} className="block text-gray-600 dark:text-gray-300 font-medium">Serviços</a>
          <a href="#sobre" onClick={() => setIsOpen(false)} className="block text-gray-600 dark:text-gray-300 font-medium">Sobre Nós</a>
          <a href="#contato" onClick={() => setIsOpen(false)} className="block text-gray-600 dark:text-gray-300 font-medium">Contato</a>
        </div>
      )}
    </nav>
  );
};

export default Navbar;
