// src/components/UserAdminSettings.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { 
  Shield, UserPlus, Trash2, X, Briefcase, Plus, Save, Edit2, Eye, Camera, KeyRound, User
} from 'lucide-vue-next'
import { useAuthStore, type UserProfile, type RolePermissions } from '../stores/auth'

const authStore = useAuthStore()
const users = ref<UserProfile[]>([])
const roles = ref<string[]>(['ADMIN', 'CEO', 'DIRETOR', 'GERENTE', 'ANALISTA'])
const newRoleName = ref('')
const newUser = ref({ username: '', email: '', password: '', role: 'ANALISTA' })

// Modal de edição
const editingUser = ref<UserProfile | null>(null)
const isEditModalOpen = ref(false)
const editForm = ref({ username: '', email: '', password: '', avatarUrl: '' })

const DEFAULT_PERMISSIONS: RolePermissions = {
  estoque: { view: true, edit: false, delete: false },
  orcamentos: { view: true, edit: false, delete: false },
  clientes: { view: true, edit: false, delete: false },
  historico: { view: true, edit: false, delete: false },
  financeiro: { view: false, edit: false, delete: false },
  config: { view: false, edit: false, delete: false },
}

const FULL_PERMISSIONS: RolePermissions = {
  estoque: { view: true, edit: true, delete: true },
  orcamentos: { view: true, edit: true, delete: true },
  clientes: { view: true, edit: true, delete: true },
  historico: { view: true, edit: true, delete: true },
  financeiro: { view: true, edit: true, delete: true },
  config: { view: true, edit: true, delete: true },
}

onMounted(() => {
  const savedUsers = localStorage.getItem('lider_users')
  if (savedUsers) {
    users.value = JSON.parse(savedUsers)
  } else {
    const admin: UserProfile = {
      id: '1',
      username: 'admin',
      email: 'admin@lider.com',
      password: '1234',
      role: 'ADMIN',
      permissions: FULL_PERMISSIONS,
      avatarUrl: ''
    } as any
    users.value = [admin]
    localStorage.setItem('lider_users', JSON.stringify(users.value))
  }
  const savedRoles = localStorage.getItem('lider_roles')
  if (savedRoles) roles.value = JSON.parse(savedRoles)
})

const saveUsers = () => {
  localStorage.setItem('lider_users', JSON.stringify(users.value))
}

const saveRoles = () => {
  localStorage.setItem('lider_roles', JSON.stringify(roles.value))
}

const handleAddRole = () => {
  if (!newRoleName.value) return
  const upper = newRoleName.value.toUpperCase()
  if (roles.value.includes(upper)) return alert('Cargo já existe')
  roles.value.push(upper)
  saveRoles()
  newRoleName.value = ''
}

const handleAddUser = () => {
  if (!newUser.value.username || !newUser.value.email) return
  const user: UserProfile = {
    id: Math.random().toString(36).substr(2, 9),
    username: newUser.value.username,
    email: newUser.value.email,
    password: newUser.value.password,
    role: newUser.value.role,
    permissions: (newUser.value.role === 'ADMIN' || newUser.value.role === 'CEO') ? FULL_PERMISSIONS : DEFAULT_PERMISSIONS
  }
  users.value.push(user)
  saveUsers()
  newUser.value = { username: '', email: '', password: '', role: 'ANALISTA' }
}

const openEditModal = (user: any) => {
  editingUser.value = user
  editForm.value = {
    username: user.username,
    email: user.email,
    password: '',
    avatarUrl: user.avatarUrl || ''
  }
  isEditModalOpen.value = true
}

const handleSaveEdit = () => {
  if (!editingUser.value) return
  const idx = users.value.findIndex(u => u.id === editingUser.value!.id)
  if (idx === -1) return

  users.value[idx].username = editForm.value.username
  users.value[idx].email = editForm.value.email
  ;(users.value[idx] as any).avatarUrl = editForm.value.avatarUrl
  if (editForm.value.password) {
    users.value[idx].password = editForm.value.password
  }
  saveUsers()

  // Atualiza sessão se for o usuário logado
  if (authStore.user && authStore.user.id === editingUser.value.id) {
    authStore.user.username = editForm.value.username
    authStore.user.email = editForm.value.email
    ;(authStore.user as any).avatarUrl = editForm.value.avatarUrl
    localStorage.setItem('lider_user', JSON.stringify(authStore.user))
  }

  isEditModalOpen.value = false
  alert('Usuário atualizado com sucesso!')
}

const togglePermission = (userId: string, tab: keyof RolePermissions, action: 'view' | 'edit' | 'delete') => {
  const user = users.value.find(u => u.id === userId)
  // ADMIN sempre mantém todas as permissões
  if (!user || user.role === 'ADMIN') return
  user.permissions[tab][action] = !user.permissions[tab][action]
  saveUsers()
}

const deleteUser = (id: string) => {
  if (confirm('Deseja excluir este usuário?')) {
    users.value = users.value.filter(u => u.id !== id)
    saveUsers()
  }
}
</script>

<template>
  <div class="space-y-8 pb-12">
    <!-- Gestão de Cargos -->
    <div class="bg-white dark:bg-slate-900 rounded-3xl p-8 border border-blue-50 dark:border-slate-800 shadow-xl">
      <div class="flex items-center gap-3 mb-6">
        <Briefcase class="text-blue-600" />
        <h3 class="text-lg font-black text-blue-900 dark:text-white">Gestão de Cargos</h3>
      </div>
      <div class="flex gap-4 items-end mb-6">
        <div class="flex-1 space-y-1">
          <label class="text-[10px] font-bold text-gray-400 uppercase">Novo Cargo</label>
          <input v-model="newRoleName" placeholder="Ex: COORDENADOR" class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-slate-800 dark:bg-slate-950 outline-none dark:text-white" />
        </div>
        <button @click="handleAddRole" class="px-6 py-2.5 bg-blue-600 text-white rounded-xl font-bold flex items-center gap-2 shadow-lg shadow-blue-500/20"><Plus :size="18" /> Criar</button>
      </div>
      <div class="flex flex-wrap gap-2">
        <div v-for="role in roles" :key="role" class="px-4 py-1.5 bg-blue-50 dark:bg-slate-800 text-blue-700 dark:text-blue-300 rounded-full font-black text-xs flex items-center gap-2 border border-blue-100 dark:border-slate-700">
          {{ role }}
          <button v-if="role !== 'ADMIN'" @click="roles = roles.filter(r => r !== role); saveRoles()" class="hover:text-red-500"><X :size="14" /></button>
        </div>
      </div>
    </div>

    <!-- Novo Usuário -->
    <div class="bg-white dark:bg-slate-900 rounded-3xl p-8 border border-blue-50 dark:border-slate-800 shadow-xl">
      <div class="flex items-center gap-3 mb-6">
        <UserPlus class="text-blue-600" />
        <h3 class="text-lg font-black text-blue-900 dark:text-white">Cadastrar Novo Usuário</h3>
      </div>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4 items-end">
        <div class="space-y-1">
          <label class="text-[10px] font-bold text-gray-400 uppercase">Usuário</label>
          <input v-model="newUser.username" class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-slate-800 dark:bg-slate-950 outline-none dark:text-white" />
        </div>
        <div class="space-y-1">
          <label class="text-[10px] font-bold text-gray-400 uppercase">E-mail</label>
          <input v-model="newUser.email" class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-slate-800 dark:bg-slate-950 outline-none dark:text-white" />
        </div>
        <div class="space-y-1">
          <label class="text-[10px] font-bold text-gray-400 uppercase">Senha</label>
          <input v-model="newUser.password" type="password" class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-slate-800 dark:bg-slate-950 outline-none dark:text-white" />
        </div>
        <div class="space-y-1">
          <label class="text-[10px] font-bold text-gray-400 uppercase">Cargo</label>
          <select v-model="newUser.role" class="w-full px-4 py-2.5 rounded-xl border border-gray-200 dark:border-slate-800 dark:bg-slate-950 outline-none dark:text-white appearance-none">
            <option v-for="r in roles" :key="r" :value="r">{{ r }}</option>
          </select>
        </div>
        <button @click="handleAddUser" class="px-6 py-2.5 bg-blue-600 text-white rounded-xl font-bold shadow-lg shadow-blue-500/20">Criar Usuário</button>
      </div>
    </div>

    <!-- Tabela de Controle de Acessos -->
    <div class="bg-white dark:bg-slate-900 rounded-3xl border border-blue-50 dark:border-slate-800 shadow-xl overflow-hidden">
      <div class="p-8 border-b dark:border-slate-800">
        <div class="flex items-center gap-3">
          <Shield class="text-blue-600" />
          <h3 class="text-lg font-black text-blue-900 dark:text-white">Controle de Acessos</h3>
        </div>
      </div>
      <div class="overflow-x-auto">
        <table class="w-full text-left border-collapse">
          <thead>
            <tr class="bg-gray-50 dark:bg-slate-800 text-[10px] font-black uppercase text-gray-500 border-b dark:border-slate-700">
              <th class="px-6 py-4">Usuário</th>
              <th v-for="t in ['estoque', 'orcamentos', 'clientes', 'historico', 'financeiro', 'config']" :key="t" class="px-6 py-4 text-center">{{ t }}</th>
              <th class="px-6 py-4 text-right">Ações</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-100 dark:divide-slate-800">
            <tr v-for="u in users" :key="u.id" class="dark:text-slate-300 hover:bg-blue-50/10 dark:hover:bg-slate-800/10 transition-colors">
              <td class="px-6 py-4">
                <!-- Avatar + Info -->
                <div class="flex items-center gap-3">
                  <div class="h-10 w-10 rounded-xl overflow-hidden bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center shrink-0">
                    <img v-if="(u as any).avatarUrl" :src="(u as any).avatarUrl" class="w-full h-full object-cover" />
                    <span v-else class="font-black text-blue-600 dark:text-blue-400 text-sm">{{ u.username.charAt(0).toUpperCase() }}</span>
                  </div>
                  <div>
                    <p class="font-black text-blue-900 dark:text-white">{{ u.username }}</p>
                    <p class="text-[10px] opacity-60">{{ u.email }}</p>
                    <span class="text-[10px] font-black text-blue-600 uppercase">{{ u.role }}</span>
                  </div>
                </div>
              </td>
              <td v-for="tab in (['estoque', 'orcamentos', 'clientes', 'historico', 'financeiro', 'config'] as const)" :key="tab" class="px-6 py-4">
                <div class="flex gap-1 justify-center">
                  <button v-for="a in (['view', 'edit', 'delete'] as const)" :key="a" @click="togglePermission(u.id, tab, a)"
                    :disabled="u.role === 'ADMIN'"
                    :class="[
                      'p-1.5 rounded-lg border transition-all',
                      u.permissions[tab]?.[a] 
                        ? 'bg-blue-600 border-blue-700 text-white' 
                        : 'bg-gray-100 dark:bg-slate-800 text-gray-400 opacity-40 grayscale',
                      u.role === 'ADMIN' ? 'cursor-default' : 'cursor-pointer hover:opacity-80'
                    ]">
                    <component :is="a === 'view' ? Eye : a === 'edit' ? Edit2 : Trash2" :size="12" />
                  </button>
                </div>
              </td>
              <td class="px-6 py-4 text-right">
                <div class="flex justify-end gap-2">
                  <!-- Editar — disponível para TODOS os usuários incluindo ADMIN -->
                  <button @click="openEditModal(u)" class="p-2 bg-blue-50 dark:bg-blue-900/20 text-blue-600 border border-blue-100 dark:border-blue-800 rounded-xl hover:bg-blue-600 hover:text-white transition-all">
                    <Edit2 :size="15" />
                  </button>
                  <!-- Excluir — apenas não-ADMIN -->
                  <button v-if="u.role !== 'ADMIN'" @click="deleteUser(u.id)" class="p-2 bg-red-50 text-red-400 border border-red-100 rounded-xl hover:bg-red-600 hover:text-white transition-all">
                    <Trash2 :size="15" />
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <!-- Modal Editar Usuário -->
    <div v-if="isEditModalOpen" class="fixed inset-0 z-[100] bg-slate-900/50 backdrop-blur-xl flex items-center justify-center p-4 animate-in fade-in duration-300">
      <div class="bg-white dark:bg-slate-900 rounded-[40px] w-full max-w-md shadow-2xl overflow-hidden border border-white/20 dark:border-slate-800 animate-in zoom-in-95 duration-300">
        <!-- Header Modal -->
        <div class="px-10 py-8 border-b border-gray-100 dark:border-slate-800 flex justify-between items-center bg-blue-50/30 dark:bg-slate-800/30">
          <div class="flex items-center gap-3">
            <div class="p-2 bg-blue-100 dark:bg-blue-900/30 rounded-xl">
              <User class="text-blue-600" :size="20" />
            </div>
            <div>
              <h3 class="text-xl font-black text-blue-900 dark:text-white uppercase tracking-tight">Editar Usuário</h3>
              <p class="text-[10px] text-gray-400 font-bold uppercase">{{ editingUser?.role }}</p>
            </div>
          </div>
          <button @click="isEditModalOpen = false" class="p-3 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-2xl text-gray-400 transition-all">
            <X :size="22" />
          </button>
        </div>

        <div class="p-10 space-y-6">
          <!-- Preview Avatar -->
          <div class="flex items-center gap-6">
            <div class="h-20 w-20 rounded-2xl overflow-hidden bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center shrink-0 border-4 border-blue-100 dark:border-blue-900/30">
              <img v-if="editForm.avatarUrl" :src="editForm.avatarUrl" class="w-full h-full object-cover" />
              <span v-else class="font-black text-blue-600 dark:text-blue-400 text-3xl">{{ editingUser?.username.charAt(0).toUpperCase() }}</span>
            </div>
            <div class="flex-1 space-y-1.5">
              <label class="text-[10px] font-black text-gray-400 uppercase tracking-widest flex items-center gap-1.5">
                <Camera :size="11" /> URL da Foto de Perfil
              </label>
              <input v-model="editForm.avatarUrl" type="text" placeholder="https://..." class="w-full px-4 py-3 rounded-xl border border-gray-100 dark:border-slate-800 bg-gray-50 dark:bg-slate-950 outline-none focus:ring-2 focus:ring-blue-500 font-bold text-xs dark:text-white" />
            </div>
          </div>

          <!-- Nome -->
          <div class="space-y-1.5">
            <label class="text-[10px] font-black text-gray-400 uppercase tracking-widest flex items-center gap-1.5">
              <User :size="11" /> Nome de Usuário
            </label>
            <input v-model="editForm.username" type="text" class="w-full px-5 py-4 rounded-2xl bg-gray-50 dark:bg-slate-950 border border-gray-100 dark:border-slate-800 outline-none focus:ring-4 focus:ring-blue-100 dark:focus:ring-blue-900/20 font-black text-sm dark:text-white transition-all" />
          </div>

          <!-- E-mail -->
          <div class="space-y-1.5">
            <label class="text-[10px] font-black text-gray-400 uppercase tracking-widest">E-mail</label>
            <input v-model="editForm.email" type="email" class="w-full px-5 py-4 rounded-2xl bg-gray-50 dark:bg-slate-950 border border-gray-100 dark:border-slate-800 outline-none focus:ring-4 focus:ring-blue-100 font-black text-sm dark:text-white transition-all" />
          </div>

          <!-- Nova Senha -->
          <div class="space-y-1.5">
            <label class="text-[10px] font-black text-gray-400 uppercase tracking-widest flex items-center gap-1.5">
              <KeyRound :size="11" /> Nova Senha <span class="text-gray-300 font-normal normal-case">(deixe em branco para manter)</span>
            </label>
            <input v-model="editForm.password" type="password" placeholder="••••••••" class="w-full px-5 py-4 rounded-2xl bg-gray-50 dark:bg-slate-950 border border-gray-100 dark:border-slate-800 outline-none focus:ring-4 focus:ring-blue-100 font-black text-sm dark:text-white transition-all" />
          </div>
        </div>

        <div class="px-10 py-8 bg-gray-50 dark:bg-slate-800/30 border-t border-gray-100 dark:border-slate-800 flex justify-end gap-3">
          <button @click="isEditModalOpen = false" class="px-6 py-3 font-black text-gray-400 uppercase text-xs hover:text-gray-600">Cancelar</button>
          <button @click="handleSaveEdit" class="px-10 py-4 bg-blue-600 hover:bg-blue-700 text-white rounded-2xl font-black uppercase text-xs tracking-widest shadow-2xl shadow-blue-500/30 active:scale-95 transition-all flex items-center gap-2">
            <Save :size="16" /> Salvar Alterações
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/UserAdminSettings.tsx
"use client";

import React from 'react';
import { Shield, UserPlus, Trash2, Check, X, Lock, Eye, Edit2, AlertCircle, Briefcase, Plus, Mail, Save } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { showSuccess, showError } from '@/utils/toast';

export interface Permission {
  view: boolean;
  edit: boolean;
  delete: boolean;
}

export interface RolePermissions {
  estoque: Permission;
  orcamentos: Permission;
  clientes: Permission;
  historico: Permission;
  config: Permission;
}

export interface UserProfile {
  id: string;
  username: string;
  email: string;
  password?: string;
  role: string;
  permissions: RolePermissions;
}

const DEFAULT_PERMISSIONS: RolePermissions = {
  estoque: { view: true, edit: false, delete: false },
  orcamentos: { view: true, edit: false, delete: false },
  clientes: { view: true, edit: false, delete: false },
  historico: { view: true, edit: false, delete: false },
  config: { view: false, edit: false, delete: false },
};

const FULL_PERMISSIONS: RolePermissions = {
  estoque: { view: true, edit: true, delete: true },
  orcamentos: { view: true, edit: true, delete: true },
  clientes: { view: true, edit: true, delete: true },
  historico: { view: true, edit: true, delete: true },
  config: { view: true, edit: true, delete: true },
};

const UserAdminSettings = () => {
  const [users, setUsers] = React.useState<UserProfile[]>([]);
  const [roles, setRoles] = React.useState<string[]>(['ADMIN', 'CEO', 'DIRETOR', 'GERENTE', 'ANALISTA']);
  const [newRoleName, setNewRoleName] = React.useState('');
  const [newUser, setNewUser] = React.useState({ username: '', email: '', password: '', role: 'ANALISTA' });
  
  const [editingUser, setEditingUser] = React.useState<UserProfile | null>(null);
  const [isEditModalOpen, setIsEditModalOpen] = React.useState(false);

  React.useEffect(() => {
    const savedUsers = localStorage.getItem('lider_users');
    if (savedUsers) setUsers(JSON.parse(savedUsers));
    else {
      const admin: UserProfile = { 
        id: '1', 
        username: 'admin', 
        email: 'admin@lider.com',
        password: '1234',
        role: 'ADMIN', 
        permissions: FULL_PERMISSIONS 
      };
      setUsers([admin]);
      localStorage.setItem('lider_users', JSON.stringify([admin]));
    }

    const savedRoles = localStorage.getItem('lider_roles');
    if (savedRoles) setRoles(JSON.parse(savedRoles));
  }, []);

  const saveUsers = (updatedUsers: UserProfile[]) => {
    setUsers(updatedUsers);
    localStorage.setItem('lider_users', JSON.stringify(updatedUsers));
  };

  const saveRoles = (updatedRoles: string[]) => {
    setRoles(updatedRoles);
    localStorage.setItem('lider_roles', JSON.stringify(updatedRoles));
  };

  const handleAddRole = () => {
    if (!newRoleName) return;
    const upperRole = newRoleName.toUpperCase();
    if (roles.includes(upperRole)) {
      showError('Este cargo já existe.');
      return;
    }
    const updatedRoles = [...roles, upperRole];
    saveRoles(updatedRoles);
    setNewRoleName('');
    showSuccess('Novo cargo criado!');
  };

  const handleDeleteRole = (roleToDelete: string) => {
    if (roleToDelete === 'ADMIN') {
      showError('O cargo ADMIN não pode ser excluído.');
      return;
    }
    if (users.some(u => u.role === roleToDelete)) {
      showError('Não é possível excluir um cargo que possui usuários vinculados.');
      return;
    }
    const updatedRoles = roles.filter(r => r !== roleToDelete);
    saveRoles(updatedRoles);
    showSuccess('Cargo excluído.');
  };

  const handleAddUser = () => {
    if (!newUser.username || !newUser.email || !newUser.password) {
      showError('Preencha todos os campos (Nome, E-mail e Senha).');
      return;
    }
    
    if (users.some(u => u.username === newUser.username || u.email === newUser.email)) {
      showError('Nome de usuário ou e-mail já cadastrado.');
      return;
    }

    const user: UserProfile = {
      id: Math.random().toString(36).substr(2, 9),
      username: newUser.username,
      email: newUser.email,
      password: newUser.password,
      role: newUser.role,
      permissions: (newUser.role === 'ADMIN' || newUser.role === 'CEO') ? FULL_PERMISSIONS : DEFAULT_PERMISSIONS
    };
    saveUsers([...users, user]);
    setNewUser({ username: '', email: '', password: '', role: roles[0] || 'ANALISTA' });
    showSuccess('Usuário criado com sucesso!');
  };

  const handleEditUser = (user: UserProfile) => {
    setEditingUser({ ...user });
    setIsEditModalOpen(true);
  };

  const handleSaveUserEdit = () => {
    if (!editingUser) return;
    
    if (!editingUser.username || !editingUser.email) {
      showError('Nome e E-mail são obrigatórios.');
      return;
    }

    const updatedUsers = users.map(u => u.id === editingUser.id ? editingUser : u);
    saveUsers(updatedUsers);
    setIsEditModalOpen(false);
    showSuccess('Dados do usuário atualizados!');
  };

  const togglePermission = (userId: string, tab: keyof RolePermissions, action: keyof Permission) => {
    const updated = users.map(u => {
      if (u.id === userId) {
        const newPerms = { ...u.permissions };
        newPerms[tab] = { ...newPerms[tab], [action]: !newPerms[tab][action] };
        return { ...u, permissions: newPerms };
      }
      return u;
    });
    saveUsers(updated);
  };

  const deleteUser = (id: string) => {
    if (window.confirm('Excluir este usuário?')) {
      saveUsers(users.filter(u => u.id !== id));
    }
  };

  return (
    <div className="space-y-8">
      {/* GESTÃO DE CARGOS */}
      <Card className="border-blue-100 dark:border-slate-800 shadow-md dark:bg-slate-900">
        <CardHeader className="bg-blue-50/50 dark:bg-slate-800/50 border-b border-blue-50 dark:border-slate-800">
          <CardTitle className="text-lg flex items-center gap-2 text-blue-900 dark:text-white">
            <Briefcase className="text-blue-600" /> Gestão de Cargos (Hierarquias)
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-6 space-y-6">
          <div className="flex gap-4 items-end">
            <div className="flex-1 space-y-1">
              <label className="text-[10px] font-bold text-gray-400 uppercase">Nome do Novo Cargo</label>
              <Input 
                placeholder="Ex: COORDENADOR" 
                value={newRoleName} 
                onChange={e => setNewRoleName(e.target.value)}
                className="dark:bg-slate-950 dark:border-slate-800"
              />
            </div>
            <Button onClick={handleAddRole} className="bg-blue-600">
              <Plus className="mr-2 h-4 w-4" /> Criar Cargo
            </Button>
          </div>

          <div className="flex flex-wrap gap-2">
            {roles.map(role => (
              <div key={role} className="flex items-center gap-2 bg-white dark:bg-slate-950 border border-blue-100 dark:border-slate-800 px-3 py-1.5 rounded-lg shadow-sm">
                <span className="text-xs font-black text-blue-900 dark:text-blue-400">{role}</span>
                {role !== 'ADMIN' && (
                  <button onClick={() => handleDeleteRole(role)} className="text-red-400 hover:text-red-600">
                    <X size={14} />
                  </button>
                )}
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* NOVO USUÁRIO */}
      <Card className="border-blue-100 dark:border-slate-800 shadow-md dark:bg-slate-900">
        <CardHeader className="bg-blue-50/50 dark:bg-slate-800/50 border-b border-blue-50 dark:border-slate-800">
          <CardTitle className="text-lg flex items-center gap-2 text-blue-900 dark:text-white">
            <UserPlus className="text-blue-600" /> Novo Usuário
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-6">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-4 items-end">
            <div className="space-y-1">
              <label className="text-[10px] font-bold text-gray-400 uppercase">Nome de Usuário</label>
              <Input 
                placeholder="Ex: joao.silva" 
                value={newUser.username} 
                onChange={e => setNewUser({...newUser, username: e.target.value})}
                className="dark:bg-slate-950 dark:border-slate-800"
              />
            </div>
            <div className="space-y-1">
              <label className="text-[10px] font-bold text-gray-400 uppercase">E-mail</label>
              <Input 
                type="email"
                placeholder="email@lider.com" 
                value={newUser.email} 
                onChange={e => setNewUser({...newUser, email: e.target.value})}
                className="dark:bg-slate-950 dark:border-slate-800"
              />
            </div>
            <div className="space-y-1">
              <label className="text-[10px] font-bold text-gray-400 uppercase">Senha de Acesso</label>
              <Input 
                type="password"
                placeholder="Defina uma senha" 
                value={newUser.password} 
                onChange={e => setNewUser({...newUser, password: e.target.value})}
                className="dark:bg-slate-950 dark:border-slate-800"
              />
            </div>
            <div className="space-y-1">
              <label className="text-[10px] font-bold text-gray-400 uppercase">Cargo / Hierarquia</label>
              <Select value={newUser.role} onValueChange={(v) => setNewUser({...newUser, role: v})}>
                <SelectTrigger className="dark:bg-slate-950 dark:border-slate-800"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {roles.map(role => (
                    <SelectItem key={role} value={role}>{role}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <Button onClick={handleAddUser} className="bg-blue-600 w-full">
              Criar Usuário
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* TABELA DE PERMISSÕES */}
      <Card className="border-blue-100 dark:border-slate-800 shadow-md overflow-hidden dark:bg-slate-900">
        <CardHeader className="bg-blue-50/50 dark:bg-slate-800/50 border-b border-blue-50 dark:border-slate-800">
          <CardTitle className="text-lg flex items-center gap-2 text-blue-900 dark:text-white">
            <Shield className="text-blue-600" /> Controle de Acessos
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <Table>
              <TableHeader>
                <TableRow className="bg-gray-50 dark:bg-slate-800/30">
                  <TableHead className="w-[250px] font-bold">Usuário / E-mail</TableHead>
                  <TableHead className="text-center font-bold">Estoque</TableHead>
                  <TableHead className="text-center font-bold">Orçamentos</TableHead>
                  <TableHead className="text-center font-bold">Clientes</TableHead>
                  <TableHead className="text-center font-bold">Histórico</TableHead>
                  <TableHead className="text-center font-bold">Config</TableHead>
                  <TableHead className="text-right font-bold">Ações</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {users.map((user) => (
                  <TableRow key={user.id} className="hover:bg-blue-50/20 dark:hover:bg-slate-800/20">
                    <TableCell>
                      <div className="flex flex-col">
                        <span className="font-bold text-blue-900 dark:text-white">{user.username}</span>
                        <span className="text-[10px] text-gray-500 dark:text-gray-400">{user.email}</span>
                        <span className="text-[10px] font-black text-blue-500 uppercase tracking-tighter mt-1">{user.role}</span>
                      </div>
                    </TableCell>
                    
                    {(['estoque', 'orcamentos', 'clientes', 'historico', 'config'] as const).map((tab) => (
                      <TableCell key={tab} className="text-center">
                        <div className="flex gap-1 justify-center">
                          <PermissionToggle 
                            active={user.permissions[tab].view} 
                            icon={<Eye size={12} />} 
                            label="Ver"
                            onClick={() => togglePermission(user.id, tab, 'view')}
                            disabled={user.role === 'ADMIN'}
                          />
                          <PermissionToggle 
                            active={user.permissions[tab].edit} 
                            icon={<Edit2 size={12} />} 
                            label="Edit"
                            onClick={() => togglePermission(user.id, tab, 'edit')}
                            disabled={user.role === 'ADMIN'}
                          />
                          <PermissionToggle 
                            active={user.permissions[tab].delete} 
                            icon={<Trash2 size={12} />} 
                            label="Del"
                            onClick={() => togglePermission(user.id, tab, 'delete')}
                            disabled={user.role === 'ADMIN'}
                          />
                        </div>
                      </TableCell>
                    ))}

                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <Button variant="ghost" size="sm" className="text-blue-600 dark:text-blue-400" onClick={() => handleEditUser(user)}>
                          <Edit2 size={16} />
                        </Button>
                        {user.role !== 'ADMIN' && (
                          <Button variant="ghost" size="sm" className="text-red-500" onClick={() => deleteUser(user.id)}>
                            <Trash2 size={16} />
                          </Button>
                        )}
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>

      {/* MODAL DE EDIÇÃO DE USUÁRIO */}
      <Dialog open={isEditModalOpen} onOpenChange={setIsEditModalOpen}>
        <DialogContent className="sm:max-w-[425px] dark:bg-slate-900 dark:border-slate-800">
          <DialogHeader>
            <DialogTitle className="text-blue-900 dark:text-white">Editar Perfil do Usuário</DialogTitle>
          </DialogHeader>
          {editingUser && (
            <div className="grid gap-4 py-4">
              <div className="grid gap-2">
                <label className="text-xs font-bold text-gray-400 uppercase">Nome de Usuário</label>
                <Input 
                  value={editingUser.username} 
                  onChange={(e) => setEditingUser({...editingUser, username: e.target.value})} 
                  className="dark:bg-slate-950 dark:border-slate-800"
                />
              </div>
              <div className="grid gap-2">
                <label className="text-xs font-bold text-gray-400 uppercase">E-mail</label>
                <Input 
                  type="email"
                  value={editingUser.email} 
                  onChange={(e) => setEditingUser({...editingUser, email: e.target.value})} 
                  className="dark:bg-slate-950 dark:border-slate-800"
                />
              </div>
              <div className="grid gap-2">
                <label className="text-xs font-bold text-gray-400 uppercase">Nova Senha (Deixe em branco para manter)</label>
                <Input 
                  type="password"
                  placeholder="Digite a nova senha..."
                  onChange={(e) => setEditingUser({...editingUser, password: e.target.value})} 
                  className="dark:bg-slate-950 dark:border-slate-800"
                />
              </div>
              <div className="grid gap-2">
                <label className="text-xs font-bold text-gray-400 uppercase">Cargo / Hierarquia</label>
                <Select 
                  value={editingUser.role} 
                  onValueChange={(v) => setEditingUser({...editingUser, role: v})}
                  disabled={editingUser.username === 'admin'} // Proteção para o admin principal
                >
                  <SelectTrigger className="dark:bg-slate-950 dark:border-slate-800"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    {roles.map(role => (
                      <SelectItem key={role} value={role}>{role}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsEditModalOpen(false)} className="dark:border-slate-800">Cancelar</Button>
            <Button className="bg-blue-600" onClick={handleSaveUserEdit}>
              <Save className="mr-2 h-4 w-4" /> Salvar Alterações
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

const PermissionToggle = ({ active, icon, label, onClick, disabled }: { active: boolean, icon: React.ReactNode, label: string, onClick: () => void, disabled?: boolean }) => (
  <button 
    onClick={onClick}
    disabled={disabled}
    title={label}
    className={`p-1.5 rounded-md transition-all border ${
      active 
        ? 'bg-blue-600 border-blue-700 text-white shadow-sm' 
        : 'bg-gray-100 dark:bg-slate-800 border-gray-200 dark:border-slate-700 text-gray-400 grayscale opacity-50'
    } ${disabled ? 'cursor-not-allowed opacity-30' : 'hover:scale-110'}`}
  >
    {icon}
  </button>
);

export default UserAdminSettings;
